import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "@/styles/all.css";
import { ApolloWrapper } from "@/lib/apollo/apollo-wrapper";
import { ThemeProvider } from "next-themes";
import { ConfigProvider } from "antd";
import "@ant-design/v5-patch-for-react-19";
import { AntdRegistry } from "@ant-design/nextjs-registry";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto.variable} antialiased`}>
        <ApolloWrapper>
          <ThemeProvider attribute="class">
            <AntdRegistry>
              <ConfigProvider>{children}</ConfigProvider>
            </AntdRegistry>
          </ThemeProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
}
