import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "@/styles/all.css";
import { ApolloWrapper } from "@/lib/apollo/apollo-wrapper";
import { AntdStyledComponentsRegistry } from "@/lib/antd/AntdStyledComponentsRegistry";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        <ApolloWrapper>
          <AntdStyledComponentsRegistry>
            {children}
          </AntdStyledComponentsRegistry>
        </ApolloWrapper>
      </body>
    </html>
  );
}
